language: python
python:
    - "2.7"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install sdl1.2debian -y
    - sudo apt-get install libsdl-ttf2.0-dev -y
install:
    - make build
    - pip install -r requirements/travis-requirements.txt
    - pip install coveralls

script:
     make coverage_travis

after_success:
     coveralls
